### ISSUE TITLE
Latest releases don't run in WS11WineCX64Bit19.0.1 Wine engine

### ISSUE THREAD

**Issue by riggs** [DrazharLn/pracx#29]
"wine: Bad EXE format for Z:\Users\riggs\Downloads\PRACX.v1.11.exe."

Same error with 1.10.

Note that SMACX_UP_v2.1_Installer.exe runs fine. Maybe there's differing compiler flags or something?

**Comment by DrazharLn** [comment]
I think this was fixed by generating 32bit installers.
